# .github/workflows/android.yml
name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer android debug
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ./bin/*.apk
